### PR TITLE
Docs: Migrate to Fumadocs

### LINKED ISSUE #180: docs: Use a documentation framework for docs
Just noticed Content Collections on GitHub, thanks for the nice library!

## The Problem

The current docs of Content Collection doesn't support search, and I think it can look better with a docs framework.

I understand some maintainers may prefer a simple docs implementation, so please tell me if you have any opinions about the docs. 

## The Solution

I want to migrate the docs to Fumadocs, and is willing to submit a PR:

- Fumadocs supports Content Collections
- It is very flexible, and is dedicated on Next.js (which the docs is using now)

## Alternatives

Other docs frameworks like Nextra and Vitepress may also be a good option.

### PR DESCRIPTION
**Pull request by fuma-nama**
This is a large rewrite to the docs, since some components may no longer fit into the design of Fumadocs (font size/weight etc.), or we have a better way to handle the same thing with it.

Summary:

- Light/Dark mode supported
- The default background is slightly changed, a bit darker on dark mode
- Document Search + Table of Contents

Closes #180

### CODE REVIEW

**Comment by sdorra** [comment]
@fuma-nama First of all, that looks amazing. I like the whole look and feel; even the light mode looks pretty good. But there are a few things I like more about the current page:

- The package manager chooser has stored the chosen package manager in local storage, and the next time the chooser is shown, regardless of the page, the correct package manager is pre-selected.
-  I think the page should have a max-width that includes the navigation and the table of contents. If the page is very wide, it does not look good with navigation on the left, the table of contents on the right, and the content with a lot of white space in the middle.
-  I liked the single menu point for the quick start with framework icons and the selector in the upper right. I like to keep the navigation menu entries small, and I think the instructions before the framework selection make sense.
-  I also like the samples chooser with the filter above and the single navigation entry. I plan to create many more samples, and I think it does not make much sense to put them all in the navbar. Are the samples not searchable?

**Comment by fuma-nama** [comment]
> The package manager chooser has stored the chosen package manager in local storage, and the next time the chooser is shown, regardless of the page, the correct package manager is pre-selected.

Oops it's possible but I forgot to enable it, thanks for mentioning.

> I think the page should have a max-width that includes the navigation and the table of contents. If the page is very wide, it does not look good with navigation on the left, the table of contents on the right, and the content with a lot of white space in the middle.

I personally love to leave more space to the content, so the navigation elements are afar from content. Will change that later.

> and I think the instructions before the framework selection make sense.

I think we can combine the "usage" page and "frameworks" page, so users after reading a short introduction of Content Collections can pick a framework or see the usage.

> I also like the samples chooser with the filter above and the single navigation entry. I plan to create many more samples, and I think it does not make much sense to put them all in the navbar.

Perhaps we can separate this from the docs? We can create a samples page which is similar to the [Vercel Templates](https://vercel.com/templates) site, it would be pretty cool.

> Are the samples not searchable?

I didn't add them to search. Because if we have a filter for samples, adding them the document search might be a bit unnecessary

**Comment by fuma-nama** [comment]
Since Fumadocs UI isn't designed to have a max width on layout (like you've mentioned), it might not look ideal and I disabled collapsible sidebar.

All problems are solved

**Comment by sdorra** [comment]
@fuma-nama Thank you very much. It looks really awesome. I need to have a closer look at some details and make some changes on my own, but I think I will merge it over the weekend or on Monday.

**Pull request merged**
